import type { Product, StoreData, User } from "./types";

function stock(sizes: string[], qty = 8): Record<string, number> {
  return Object.fromEntries(sizes.map((s) => [s, qty]));
}

const shoe = ["6", "7", "8", "9", "10", "11"] as const;
const apparel = ["S", "M", "L", "XL"] as const;

const now = new Date().toISOString();

export const seedProducts: Product[] = [
  {
    id: "p1",
    slug: "louis-trainer-grey-white",
    name: "Louis Trainer Grey White",
    price: 49.99,
    category: "footwear",
    description: "Monogram denim and white leather Louis trainer. Maison staple for clean rotation.",
    image: "/products/fw01.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 6),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p2",
    slug: "louis-trainer-black-white",
    name: "Louis Trainer Black White",
    price: 49.99,
    category: "footwear",
    description: "Black and white Louis trainer with embossed monogram panels. High-contrast house classic.",
    image: "/products/fw02.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p3",
    slug: "door-30-trainer-white-black",
    name: "Door 30 Trainer White Black",
    price: 49.99,
    category: "footwear",
    description: "Door 30 in black with white CD piping. Technical mesh, dust bag presentation.",
    image: "/products/fw03.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 7),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p4",
    slug: "door-30-trainer-black",
    name: "Door 30 Trainer Black",
    price: 49.99,
    category: "footwear",
    description: "All-black Door 30 with reflective CD mark. Quiet luxury on concrete.",
    image: "/products/fw04.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p5",
    slug: "door-22-trainer-black",
    name: "Door 22 Trainer Black",
    price: 49.99,
    category: "footwear",
    description: "Door 22 black with silver overlays. Chunky sole, maison plaque detail.",
    image: "/products/fw05.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 9),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p6",
    slug: "door-30-trainer-white",
    name: "Door 30 Trainer White",
    price: 49.99,
    category: "footwear",
    description: "Crisp white Door 30 with tonal CD mark. Editorial white-on-stone finish.",
    image: "/products/fw06.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p7",
    slug: "door-22-trainer-white",
    name: "Door 22 Trainer White",
    price: 49.99,
    category: "footwear",
    description: "White and silver Door 22. Cream architecture sole, spare laces included.",
    image: "/products/fw07.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 6),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p8",
    slug: "door-22-trainer-blue-grey",
    name: "Door 22 Trainer Blue Grey",
    price: 49.99,
    category: "footwear",
    description: "Door 22 in grey, cream and royal blue. Technical mesh with maison midsole insert.",
    image: "/products/fw08.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 3),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p9",
    slug: "fjord-grey-asics",
    name: "Fjord Grey Asics",
    price: 45,
    category: "footwear",
    description: "Fjord grey Asics with cream mesh and suede overlays. Boxed runner presentation.",
    image: "/products/fw09.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 8),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p10",
    slug: "silver-asics",
    name: "Silver Asics",
    price: 45,
    category: "footwear",
    description: "Metallic silver Asics. Catch the light.",
    image: "/products/fw10.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p11",
    slug: "baby-blue-asics",
    name: "Baby Blue Asics",
    price: 45,
    category: "footwear",
    description: "Soft baby blue Asics for clean summer looks.",
    image: "/products/fw11.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p12",
    slug: "black-asics",
    name: "Black Asics",
    price: 45,
    category: "footwear",
    description: "Black Gel-Kayano runner with metallic gel pods. Technical night-shift essential.",
    image: "/products/fw12.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 10),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p13",
    slug: "grey-asics",
    name: "Grey Asics",
    price: 45,
    category: "footwear",
    description: "Neutral grey Asics that go with everything.",
    image: "/products/fw13.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 7),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p14",
    slug: "blue-asics",
    name: "Blue Asics",
    price: 45,
    category: "footwear",
    description: "Deep blue Asics runner.",
    image: "/products/fw14.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p15",
    slug: "grey-air-max-95",
    name: "Grey Air Max 95",
    price: 45,
    category: "footwear",
    description: "Grey gradient Air Max 95 with red-box presentation. Layered runner classic.",
    image: "/products/fw15.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 6),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p16",
    slug: "black-air-max-95",
    name: "Black Air Max 95",
    price: 45,
    category: "footwear",
    description: "Black and grey Air Max 95. Gradient panels, clear air units, boxed.",
    image: "/products/fw16.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p17",
    slug: "black-p6000",
    name: "Black P6000",
    price: 45,
    category: "footwear",
    description: "Black and silver P6000. Early-2000s runner energy, boxed on concrete.",
    image: "/products/fw17.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 8),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p18",
    slug: "navy-p6000",
    name: "Navy P6000",
    price: 45,
    category: "footwear",
    description: "Navy P6000 with layered mesh.",
    image: "/products/fw18.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 3),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p19",
    slug: "carbon-p6000",
    name: "Carbon P6000",
    price: 45,
    category: "footwear",
    description: "Carbon grey P6000.",
    image: "/products/fw19.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p20",
    slug: "white-p6000",
    name: "White P6000",
    price: 45,
    category: "footwear",
    description: "White P6000 clean pair.",
    image: "/products/fw20.jpg",
    sizes: [...shoe],
    inventory: stock([...shoe], 7),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p21",
    slug: "grey-essentials-tracksuit",
    name: "Grey Essentials Tracksuit",
    price: 45,
    category: "tracksuits",
    description: "Soft grey essentials tracksuit. Top and bottoms set.",
    image: "/products/ts01.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 6),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p22",
    slug: "black-essentials-tracksuit",
    name: "Black Essentials Tracksuit",
    price: 45,
    category: "tracksuits",
    description: "Black essentials tracksuit. Core piece.",
    image: "/products/ts02.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 8),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p23",
    slug: "black-goose-tracksuit",
    name: "Black Goose Tracksuit",
    price: 30,
    category: "tracksuits",
    description: "Black goose-inspired tracksuit set.",
    image: "/products/ts03.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p24",
    slug: "grey-goose-tracksuit",
    name: "Grey Goose Tracksuit",
    price: 30,
    category: "tracksuits",
    description: "Grey goose tracksuit for chill days.",
    image: "/products/ts04.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p25",
    slug: "rl-tracksuit-black",
    name: "RL Tracksuit Black",
    price: 32,
    category: "tracksuits",
    description: "RL-style black tracksuit.",
    image: "/products/ts05.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 6),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p26",
    slug: "rl-tracksuit-navy",
    name: "RL Tracksuit Navy",
    price: 32,
    category: "tracksuits",
    description: "Navy RL tracksuit set.",
    image: "/products/ts06.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 5),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p27",
    slug: "grey-stone-tracksuit",
    name: "Grey Stone Tracksuit",
    price: 27,
    category: "tracksuits",
    description: "Stone island inspired grey set.",
    image: "/products/ts07.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 7),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p28",
    slug: "black-stone-tracksuit",
    name: "Black Stone Tracksuit",
    price: 27,
    category: "tracksuits",
    description: "Black stone tracksuit.",
    image: "/products/ts08.jpg",
    sizes: [...apparel],
    inventory: stock([...apparel], 4),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p29",
    slug: "goyard-messenger-black",
    name: "Goyard Messenger Black",
    price: 40,
    category: "accessories",
    description: "Black messenger bag. Crossbody daily carry.",
    image: "/products/ac01.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 12),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p30",
    slug: "goyard-messenger-grey",
    name: "Goyard Messenger Grey",
    price: 40,
    category: "accessories",
    description: "Grey messenger bag.",
    image: "/products/ac02.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 9),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p31",
    slug: "door-messenger-black",
    name: "Door Messenger Black",
    price: 40,
    category: "accessories",
    description: "Door black messenger.",
    image: "/products/ac03.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 8),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p32",
    slug: "louis-belt-style-1",
    name: "Louis Belt Style 1",
    price: 25,
    category: "accessories",
    description: "Louis-style belt. Adjustable.",
    image: "/products/ac04.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 15),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p33",
    slug: "louis-shades-style-1",
    name: "Louis Shades Style 1",
    price: 15,
    category: "accessories",
    description: "Louis-style sunglasses.",
    image: "/products/ac05.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 20),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "p34",
    slug: "burbs-shades",
    name: "Burbs Shades",
    price: 15,
    category: "accessories",
    description: "Classic burbs shades.",
    image: "/products/ac06.jpg",
    sizes: ["One Size"],
    inventory: stock(["One Size"], 18),
    active: true,
    createdAt: now,
    updatedAt: now,
  },
];

/** password: culture123 */
export const seedUsers: User[] = [
  {
    id: "u-admin",
    email: "admin@culturecloset.com",
    name: "Store Admin",
    passwordHash:
      "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
    role: "admin",
    createdAt: now,
  },
  {
    id: "u-demo",
    email: "demo@culturecloset.com",
    name: "Demo Customer",
    passwordHash:
      "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
    role: "customer",
    createdAt: now,
  },
];

export const seedData: StoreData = {
  products: seedProducts,
  users: seedUsers,
  orders: [],
};
